export default {

	EN: {
		skills: 'Skills',
		portfolio: 'Portfolio',
		video: 'Video',
		price: 'Price',
		contacts: 'Contacts',
		'hero-title': 'Alexa Rise',
		'hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
		hire: 'Hire me',
		'skills-title-1': 'Digital photography',
		'skills-paragraph-1': 'High-quality photos in the studio and on the nature',
		'skills-title-2': 'Video shooting',
		'skills-paragraph-2': 'Capture your moments so that they always stay with you',
		'skills-title-3': 'Retouch',
		'skills-paragraph-3': 'I strive to make photography surpass reality',
		'skills-title-4': 'Audio',
		'skills-paragraph-4': 'Professional sounds recording for video, advertising, portfolio',
		winter: 'Winter',
		spring: 'Spring',
		summer: 'Summer',
		autumn: 'Autumn',
		'price-title-1': 'Standard',
		'price-description-1-text-1': 'One location',
		'price-description-1-text-2': '120 photos in color',
		'price-description-1-text-3': '12 photos in retouch',
		'price-description-1-text-4': 'Readiness 2-3 weeks',
		'price-description-1-text-5': 'Make up, visage',
		'price-button': 'Order shooting',
		'price-title-2': 'Premium',
		'price-description-2-text-1': 'One or two locations',
		'price-description-2-text-2': '200 photos in color',
		'price-description-2-text-3': '20 photos in retouch',
		'price-description-2-text-4': 'Readiness 1-2 weeks',
		'price-description-2-text-5': 'Make up, visage',
		'price-title-3': 'Gold',
		'price-description-3-text-1': 'Three locations or more',
		'price-description-3-text-2': '300 photos in color',
		'price-description-3-text-3': '50 photos in retouch',
		'price-description-3-text-4': 'Readiness 1 week',
		'price-description-3-text-5': 'Make up, visage,  hairstyle',
		'contact-me': 'Contact me',
		'input-mail': 'E-mail',
		'input-tel': 'Phone',
		'textarea': 'Message',
		'contact-button': 'Send message'
	},

	RU: {
		skills: 'Навыки',
		portfolio: 'Портфолио',
		video: 'Видео',
		price: 'Стоимость',
		contacts: 'Контакты',
		'hero-title': 'Алекса Райc',
		'hero-text': 'Сохраните искренние эмоции, романтические чувства и счастливые моменты жизни вместе с профессиональным фотографом Алексой Райс.',
		hire: 'Пригласить',
		'skills-title-1': 'Фотосъемка',
		'skills-paragraph-1': 'Высококачественные фотографии в студии и на природе',
		'skills-title-2': 'Видеосъемка',
		'skills-paragraph-2': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
		'skills-title-3': 'Ретушь',
		'skills-paragraph-3': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
		'skills-title-4': 'Звук',
		'skills-paragraph-4': 'Профессиональная запись звука для видео, рекламы, портфолио',
		winter: 'Зима',
		spring: 'Весна',
		summer: 'Лето',
		autumn: 'Осень',
		'price-title-1': 'Стандарт',
		'price-description-1-text-1': 'Одна локация',
		'price-description-1-text-2': '120 цветных фото',
		'price-description-1-text-3': '12 отретушированных фото',
		'price-description-1-text-4': 'Готовность 2-3 недели',
		'price-description-1-text-5': 'Макияж, визаж',
		'price-button': 'Заказать съемку',
		'price-title-2': 'Премиум',
		'price-description-2-text-1': 'Одна или две локации',
		'price-description-2-text-2': '200 цветных фото',
		'price-description-2-text-3': '20 отретушированных фото',
		'price-description-2-text-4': 'Готовность 1-2 недели',
		'price-description-2-text-5': 'Макияж, визаж',
		'price-title-3': 'Голд',
		'price-description-3-text-1': 'Три локации или больше',
		'price-description-3-text-2': '300 цветных фото',
		'price-description-3-text-3': '50 отретушированных фото',
		'price-description-3-text-4': 'Готовность одна неделя',
		'price-description-3-text-5': 'Макияж, визаж,  прическа',
		'contact-me': 'Свяжитесь со мной',
		'input-mail': 'Эл.почта',
		'input-tel': 'Телефон',
		'textarea': 'Сообщение',
		'contact-button': 'Отправить'
	}

}